/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Database;

/**
 *
 * @author nunya
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuTab = new javax.swing.JTabbedPane();
        MMOuterContainer = new javax.swing.JPanel();
        MMWelcome = new javax.swing.JLabel();
        MMinnerContainer = new javax.swing.JPanel();
        MMintroText = new javax.swing.JLabel();
        ModifyTabDescription = new javax.swing.JLabel();
        InsertTabDescription = new javax.swing.JLabel();
        QueryTabDescription = new javax.swing.JLabel();
        ModifyTabContainer = new javax.swing.JPanel();
        ModifyTableListContainer = new javax.swing.JScrollPane();
        ModifyTableList = new javax.swing.JList<>();
        lblModifyTableList = new javax.swing.JLabel();
        ModifyWarning = new javax.swing.JLabel();
        InsertTabContainer = new javax.swing.JPanel();
        InsertInstructions = new javax.swing.JLabel();
        buttonProviderTbl = new javax.swing.JButton();
        buttonPlanTbl = new javax.swing.JButton();
        buttonBenefitsTbl = new javax.swing.JButton();
        buttonPlanlvlProgramsTbl = new javax.swing.JButton();
        buttonCostShareTbl = new javax.swing.JButton();
        buttonPremiumTbl = new javax.swing.JButton();
        buttonGeoCovTbl = new javax.swing.JButton();
        buttonMOOPTbl = new javax.swing.JButton();
        buttonRefReqTbl = new javax.swing.JButton();
        buttonInNetDeductTbl = new javax.swing.JButton();
        buttonOutNetDeductTbl = new javax.swing.JButton();
        buttonBenefitCostTbl = new javax.swing.JButton();
        lvlStep1 = new javax.swing.JLabel();
        lblStep2 = new javax.swing.JLabel();
        lblStep3 = new javax.swing.JLabel();
        lblStep4 = new javax.swing.JLabel();
        lblStep5 = new javax.swing.JLabel();
        buttonOutPocketCostsTbl = new javax.swing.JButton();
        lblStep6 = new javax.swing.JLabel();
        QueryTabContainer = new javax.swing.JPanel();
        FileMenu = new javax.swing.JMenuBar();
        FileDropdown = new javax.swing.JMenu();
        HelpDropdown = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        setForeground(java.awt.Color.cyan);

        MainMenuTab.setBackground(new java.awt.Color(255, 255, 255));
        MainMenuTab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        MMOuterContainer.setBackground(new java.awt.Color(255, 255, 255));

        MMWelcome.setBackground(new java.awt.Color(255, 255, 255));
        MMWelcome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MMWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/MHBElogo.jpg"))); // NOI18N
        MMWelcome.setText("<html>Welcome to the Rate and Plan Template Database </br>for the Maryland Health Benefit Exchange</html>");

        MMinnerContainer.setBackground(new java.awt.Color(255, 255, 255));

        MMintroText.setText("<html>This application allows the user to send queries to the Rate and Plan Database to retrieve information </br> about the Insurance Plans offered by Issuers participating in the Maryland HBX. Please select and option below to continue.</html>");

        ModifyTabDescription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/mhbelogo_thumb.png"))); // NOI18N
        ModifyTabDescription.setText("<html><b>Modify Templates:</b></br> </br> This tab will allow users to modify any existing tables within the template database. Navigate to this tab if you need to update specific template information OR if you need to delete any template information from the database.</br> </br></html>");

        InsertTabDescription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/mhbelogo_thumb.png"))); // NOI18N
        InsertTabDescription.setText("<html><b>Insert Template:</b></br> </br> This tab allows users to insert a new template into the database, table by table.</br> </html>");

        QueryTabDescription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/mhbelogo_thumb.png"))); // NOI18N
        QueryTabDescription.setText("<html><b>Query Database:</b></br> </br> This tab allows users to ask specific questions of the database. Some common pre-generated queries are available and there is an option for advanced users to supply a SQL query to the database to answer more complex questions.</br> </html>");

        javax.swing.GroupLayout MMinnerContainerLayout = new javax.swing.GroupLayout(MMinnerContainer);
        MMinnerContainer.setLayout(MMinnerContainerLayout);
        MMinnerContainerLayout.setHorizontalGroup(
            MMinnerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MMinnerContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MMintroText, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(MMinnerContainerLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(MMinnerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModifyTabDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertTabDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QueryTabDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MMinnerContainerLayout.setVerticalGroup(
            MMinnerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MMinnerContainerLayout.createSequentialGroup()
                .addComponent(MMintroText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ModifyTabDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(InsertTabDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(QueryTabDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MMOuterContainerLayout = new javax.swing.GroupLayout(MMOuterContainer);
        MMOuterContainer.setLayout(MMOuterContainerLayout);
        MMOuterContainerLayout.setHorizontalGroup(
            MMOuterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MMOuterContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MMOuterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MMinnerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MMWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE))
                .addContainerGap())
        );
        MMOuterContainerLayout.setVerticalGroup(
            MMOuterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MMOuterContainerLayout.createSequentialGroup()
                .addComponent(MMWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MMinnerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainMenuTab.addTab("Main Menu", MMOuterContainer);

        ModifyTableList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Provider Table", "Plan Table", "Plan Level Programs Table", "Benefit Table", "Cost Sharing Table", "Service Cost Table", "Dates Table", "Exclusions Table", "Geographic Coverage Table", "In Network Deductible Table", "Out-of-Network Deductible Table", "Out-of-pocket Table", "Referral Required Table", "Maximum Out-of-pocket Table", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ModifyTableListContainer.setViewportView(ModifyTableList);

        lblModifyTableList.setLabelFor(ModifyTabContainer);
        lblModifyTableList.setText("Which table would you like to modify?");

        ModifyWarning.setForeground(new java.awt.Color(255, 0, 0));
        ModifyWarning.setText("<html> <b>WARNING:</b> The information housed in this database comes directly from the Issuer Templates uploaded to SERFF. The only reason a user should modify a template is to correct information that was incorrectly added to the database via either an automated process or manual data entry. This database is meant to be a source of truth for MHBE and should only ever contain information pulled directly from the templates on SERFF. Thank you.</html>");

        javax.swing.GroupLayout ModifyTabContainerLayout = new javax.swing.GroupLayout(ModifyTabContainer);
        ModifyTabContainer.setLayout(ModifyTabContainerLayout);
        ModifyTabContainerLayout.setHorizontalGroup(
            ModifyTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyTabContainerLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(ModifyTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModifyWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModifyTableList)
                    .addComponent(ModifyTableListContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        ModifyTabContainerLayout.setVerticalGroup(
            ModifyTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyTabContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ModifyWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblModifyTableList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyTableListContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        MainMenuTab.addTab("Modify Templates", ModifyTabContainer);

        InsertInstructions.setText("<html>Template data must be entered in a specific order to maintain database integrity.</br> \nPlease add data to the tables in the order provided below.</html>");

        buttonProviderTbl.setText("Provider Table");
        buttonProviderTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProviderTblActionPerformed(evt);
            }
        });

        buttonPlanTbl.setText("Plan Table");
        buttonPlanTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlanTblActionPerformed(evt);
            }
        });

        buttonBenefitsTbl.setText("Benefits Table");
        buttonBenefitsTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBenefitsTblActionPerformed(evt);
            }
        });

        buttonPlanlvlProgramsTbl.setText("Plan Level Programs Table");
        buttonPlanlvlProgramsTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlanlvlProgramsTblActionPerformed(evt);
            }
        });

        buttonCostShareTbl.setText("Cost Sharing Table");
        buttonCostShareTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCostShareTblActionPerformed(evt);
            }
        });

        buttonPremiumTbl.setText("Premium Table");
        buttonPremiumTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPremiumTblActionPerformed(evt);
            }
        });

        buttonGeoCovTbl.setText("Geographic Coverage Table");
        buttonGeoCovTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGeoCovTblActionPerformed(evt);
            }
        });

        buttonMOOPTbl.setText("Max Out of Pocket Table");
        buttonMOOPTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMOOPTblActionPerformed(evt);
            }
        });

        buttonRefReqTbl.setText("Referral Required Table");
        buttonRefReqTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefReqTblActionPerformed(evt);
            }
        });

        buttonInNetDeductTbl.setText("In Network Deductible Table");
        buttonInNetDeductTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInNetDeductTblActionPerformed(evt);
            }
        });

        buttonOutNetDeductTbl.setText("Out-of-Network Deductible Table");
        buttonOutNetDeductTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutNetDeductTblActionPerformed(evt);
            }
        });

        buttonBenefitCostTbl.setText("Benefit Service Cost Table");
        buttonBenefitCostTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBenefitCostTblActionPerformed(evt);
            }
        });

        lvlStep1.setText("Step 1:");

        lblStep2.setText("Step 2:");

        lblStep3.setText("Step 3:");

        lblStep4.setText("Step 4:");

        lblStep5.setText("Step 5:");

        buttonOutPocketCostsTbl.setText("Out of Pocket Table");
        buttonOutPocketCostsTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutPocketCostsTblActionPerformed(evt);
            }
        });

        lblStep6.setText("Step 6:");

        javax.swing.GroupLayout InsertTabContainerLayout = new javax.swing.GroupLayout(InsertTabContainer);
        InsertTabContainer.setLayout(InsertTabContainerLayout);
        InsertTabContainerLayout.setHorizontalGroup(
            InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTabContainerLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InsertTabContainerLayout.createSequentialGroup()
                        .addComponent(lblStep2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPlanTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InsertTabContainerLayout.createSequentialGroup()
                        .addComponent(lvlStep1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonProviderTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertTabContainerLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertTabContainerLayout.createSequentialGroup()
                        .addComponent(InsertInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertTabContainerLayout.createSequentialGroup()
                        .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStep3)
                            .addComponent(lblStep4)
                            .addComponent(lblStep5)
                            .addComponent(lblStep6))
                        .addGap(5, 5, 5)
                        .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonMOOPTbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonRefReqTbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonPremiumTbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonOutPocketCostsTbl, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonBenefitCostTbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonOutNetDeductTbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonInNetDeductTbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonBenefitsTbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonPlanlvlProgramsTbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonGeoCovTbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonCostShareTbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(81, 81, 81))))
        );
        InsertTabContainerLayout.setVerticalGroup(
            InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTabContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonProviderTbl)
                    .addComponent(lvlStep1))
                .addGap(18, 18, 18)
                .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPlanTbl)
                    .addComponent(lblStep2))
                .addGap(38, 38, 38)
                .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPremiumTbl)
                    .addComponent(buttonBenefitsTbl)
                    .addComponent(lblStep3)
                    .addComponent(buttonCostShareTbl))
                .addGap(51, 51, 51)
                .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBenefitCostTbl)
                    .addComponent(lblStep4)
                    .addComponent(buttonRefReqTbl)
                    .addComponent(buttonPlanlvlProgramsTbl))
                .addGap(55, 55, 55)
                .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOutNetDeductTbl)
                    .addComponent(lblStep5)
                    .addComponent(buttonMOOPTbl)
                    .addComponent(buttonGeoCovTbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(InsertTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOutPocketCostsTbl)
                    .addComponent(buttonInNetDeductTbl)
                    .addComponent(lblStep6))
                .addGap(74, 74, 74))
        );

        MainMenuTab.addTab("Insert Template", InsertTabContainer);

        javax.swing.GroupLayout QueryTabContainerLayout = new javax.swing.GroupLayout(QueryTabContainer);
        QueryTabContainer.setLayout(QueryTabContainerLayout);
        QueryTabContainerLayout.setHorizontalGroup(
            QueryTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );
        QueryTabContainerLayout.setVerticalGroup(
            QueryTabContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        MainMenuTab.addTab("Query Database", QueryTabContainer);

        FileMenu.setBackground(new java.awt.Color(255, 255, 255));
        FileMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FileDropdown.setBackground(new java.awt.Color(255, 255, 255));
        FileDropdown.setText("File");
        FileMenu.add(FileDropdown);

        HelpDropdown.setText("Edit");
        FileMenu.add(HelpDropdown);

        setJMenuBar(FileMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuTab, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProviderTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProviderTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonProviderTblActionPerformed

    private void buttonPlanTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlanTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPlanTblActionPerformed

    private void buttonBenefitsTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBenefitsTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBenefitsTblActionPerformed

    private void buttonBenefitCostTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBenefitCostTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBenefitCostTblActionPerformed

    private void buttonPremiumTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPremiumTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPremiumTblActionPerformed

    private void buttonPlanlvlProgramsTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlanlvlProgramsTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPlanlvlProgramsTblActionPerformed

    private void buttonMOOPTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMOOPTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMOOPTblActionPerformed

    private void buttonOutNetDeductTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutNetDeductTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOutNetDeductTblActionPerformed

    private void buttonCostShareTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCostShareTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCostShareTblActionPerformed

    private void buttonGeoCovTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGeoCovTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGeoCovTblActionPerformed

    private void buttonInNetDeductTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInNetDeductTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonInNetDeductTblActionPerformed

    private void buttonRefReqTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefReqTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRefReqTblActionPerformed

    private void buttonOutPocketCostsTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutPocketCostsTblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOutPocketCostsTblActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileDropdown;
    private javax.swing.JMenuBar FileMenu;
    private javax.swing.JMenu HelpDropdown;
    private javax.swing.JLabel InsertInstructions;
    private javax.swing.JPanel InsertTabContainer;
    private javax.swing.JLabel InsertTabDescription;
    private javax.swing.JPanel MMOuterContainer;
    private javax.swing.JLabel MMWelcome;
    private javax.swing.JPanel MMinnerContainer;
    private javax.swing.JLabel MMintroText;
    private javax.swing.JTabbedPane MainMenuTab;
    private javax.swing.JPanel ModifyTabContainer;
    private javax.swing.JLabel ModifyTabDescription;
    private javax.swing.JList<String> ModifyTableList;
    private javax.swing.JScrollPane ModifyTableListContainer;
    private javax.swing.JLabel ModifyWarning;
    private javax.swing.JPanel QueryTabContainer;
    private javax.swing.JLabel QueryTabDescription;
    private javax.swing.JButton buttonBenefitCostTbl;
    private javax.swing.JButton buttonBenefitsTbl;
    private javax.swing.JButton buttonCostShareTbl;
    private javax.swing.JButton buttonGeoCovTbl;
    private javax.swing.JButton buttonInNetDeductTbl;
    private javax.swing.JButton buttonMOOPTbl;
    private javax.swing.JButton buttonOutNetDeductTbl;
    private javax.swing.JButton buttonOutPocketCostsTbl;
    private javax.swing.JButton buttonPlanTbl;
    private javax.swing.JButton buttonPlanlvlProgramsTbl;
    private javax.swing.JButton buttonPremiumTbl;
    private javax.swing.JButton buttonProviderTbl;
    private javax.swing.JButton buttonRefReqTbl;
    private javax.swing.JLabel lblModifyTableList;
    private javax.swing.JLabel lblStep2;
    private javax.swing.JLabel lblStep3;
    private javax.swing.JLabel lblStep4;
    private javax.swing.JLabel lblStep5;
    private javax.swing.JLabel lblStep6;
    private javax.swing.JLabel lvlStep1;
    // End of variables declaration//GEN-END:variables
}
